-- MySQL Script generated by MySQL Workbench
-- Sun Jun  5 17:16:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idCliente` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cognome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(15) NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ordine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ordine` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ordine` (
  `id_ordine` INT NOT NULL,
  `utente_idCliente` INT NOT NULL,
  `ordinecol` VARCHAR(45) NULL,
  `stato` TINYINT NULL,
  PRIMARY KEY (`id_ordine`),
  INDEX `fk_ordine_utente1_idx` (`utente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_ordine_utente1`
    FOREIGN KEY (`utente_idCliente`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prodotto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`prodotto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`prodotto` (
  `idprodotto` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `prezzo` VARCHAR(45) NULL,
  `descrizione_breve` TEXT(100) NULL,
  `descrizione` VARCHAR(45) NULL,
  `dettagli` VARCHAR(45) NULL,
  PRIMARY KEY (`idprodotto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `idcategoria` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `categoria_idcategoria` INT NULL,
  PRIMARY KEY (`idcategoria`, `categoria_idcategoria`),
  INDEX `fk_categoria_categoria1_idx` (`categoria_idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `mydb`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria_has_prodotto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categoria_has_prodotto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categoria_has_prodotto` (
  `categoria_idcategoria` INT NOT NULL,
  `prodotto_idprodotto` INT NOT NULL,
  PRIMARY KEY (`categoria_idcategoria`, `prodotto_idprodotto`),
  INDEX `fk_categoria_has_prodotto_prodotto1_idx` (`prodotto_idprodotto` ASC) VISIBLE,
  INDEX `fk_categoria_has_prodotto_categoria1_idx` (`categoria_idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_has_prodotto_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `mydb`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categoria_has_prodotto_prodotto1`
    FOREIGN KEY (`prodotto_idprodotto`)
    REFERENCES `mydb`.`prodotto` (`idprodotto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ordine_has_prodotto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ordine_has_prodotto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ordine_has_prodotto` (
  `ordine_id_ordine` INT NOT NULL,
  `prodotto_idprodotto` INT NOT NULL,
  `prezzo` DECIMAL(5) NULL,
  `quantity` INT NULL,
  `colore` VARCHAR(45) NULL,
  `taglia` VARCHAR(45) NULL,
  PRIMARY KEY (`ordine_id_ordine`, `prodotto_idprodotto`),
  INDEX `fk_carrello_has_prodotto_prodotto1_idx` (`prodotto_idprodotto` ASC) VISIBLE,
  INDEX `fk_carrello_has_prodotto_ordine1_idx` (`ordine_id_ordine` ASC) VISIBLE,
  CONSTRAINT `fk_carrello_has_prodotto_prodotto1`
    FOREIGN KEY (`prodotto_idprodotto`)
    REFERENCES `mydb`.`prodotto` (`idprodotto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrello_has_prodotto_ordine1`
    FOREIGN KEY (`ordine_id_ordine`)
    REFERENCES `mydb`.`ordine` (`id_ordine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`indirizzo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`indirizzo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`indirizzo` (
  `città` VARCHAR(45) NULL,
  `cap` VARCHAR(5) NULL,
  `via` VARCHAR(45) NULL,
  `civico` SMALLINT(3) NULL,
  `utente registrato_idUtente` INT NOT NULL,
  PRIMARY KEY (`utente registrato_idUtente`),
  CONSTRAINT `fk_indirizzo_utente registrato1`
    FOREIGN KEY (`utente registrato_idUtente`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`immagine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`immagine` ;

CREATE TABLE IF NOT EXISTS `mydb`.`immagine` (
  `idimmagine` INT NOT NULL,
  `prodotto_idprodotto` INT NOT NULL,
  `immagine` BLOB(1000) NULL,
  PRIMARY KEY (`idimmagine`, `prodotto_idprodotto`),
  INDEX `fk_immagine_prodotto1_idx` (`prodotto_idprodotto` ASC) VISIBLE,
  CONSTRAINT `fk_immagine_prodotto1`
    FOREIGN KEY (`prodotto_idprodotto`)
    REFERENCES `mydb`.`prodotto` (`idprodotto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gruppi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`gruppi` ;

CREATE TABLE IF NOT EXISTS `mydb`.`gruppi` (
  `idgruppi` INT NOT NULL,
  PRIMARY KEY (`idgruppi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servizi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`servizi` ;

CREATE TABLE IF NOT EXISTS `mydb`.`servizi` (
  `idservizi` INT NOT NULL,
  PRIMARY KEY (`idservizi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gruppi_has_servizi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`gruppi_has_servizi` ;

CREATE TABLE IF NOT EXISTS `mydb`.`gruppi_has_servizi` (
  `gruppi_idgruppi` INT NOT NULL,
  `servizi_idservizi` INT NOT NULL,
  PRIMARY KEY (`gruppi_idgruppi`, `servizi_idservizi`),
  INDEX `fk_gruppi_has_servizi_servizi1_idx` (`servizi_idservizi` ASC) VISIBLE,
  INDEX `fk_gruppi_has_servizi_gruppi1_idx` (`gruppi_idgruppi` ASC) VISIBLE,
  CONSTRAINT `fk_gruppi_has_servizi_gruppi1`
    FOREIGN KEY (`gruppi_idgruppi`)
    REFERENCES `mydb`.`gruppi` (`idgruppi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gruppi_has_servizi_servizi1`
    FOREIGN KEY (`servizi_idservizi`)
    REFERENCES `mydb`.`servizi` (`idservizi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Utente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Utente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Utente` (
  `idUtente` INT NOT NULL,
  `cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idUtente`, `cliente_idCliente`),
  INDEX `fk_Utente_cliente1_idx` (`cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Utente_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrello`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`carrello` ;

CREATE TABLE IF NOT EXISTS `mydb`.`carrello` (
  `idUtente` INT NOT NULL,
  `Utente_idUtente` INT NOT NULL,
  `Utente_cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idUtente`, `Utente_idUtente`, `Utente_cliente_idCliente`),
  INDEX `fk_carrello_Utente1_idx` (`Utente_idUtente` ASC, `Utente_cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_carrello_Utente1`
    FOREIGN KEY (`Utente_idUtente` , `Utente_cliente_idCliente`)
    REFERENCES `mydb`.`Utente` (`idUtente` , `cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Utente_has_gruppi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Utente_has_gruppi` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Utente_has_gruppi` (
  `Utente_idUtente` INT NOT NULL,
  `gruppi_idgruppi` INT NOT NULL,
  PRIMARY KEY (`Utente_idUtente`, `gruppi_idgruppi`),
  INDEX `fk_Utente_has_gruppi_gruppi1_idx` (`gruppi_idgruppi` ASC) VISIBLE,
  INDEX `fk_Utente_has_gruppi_Utente1_idx` (`Utente_idUtente` ASC) VISIBLE,
  CONSTRAINT `fk_Utente_has_gruppi_Utente1`
    FOREIGN KEY (`Utente_idUtente`)
    REFERENCES `mydb`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utente_has_gruppi_gruppi1`
    FOREIGN KEY (`gruppi_idgruppi`)
    REFERENCES `mydb`.`gruppi` (`idgruppi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrello_has_prodotto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`carrello_has_prodotto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`carrello_has_prodotto` (
  `carrello_idUtente` INT NOT NULL,
  `carrello_Utente_idUtente` INT NOT NULL,
  `carrello_Utente_cliente_idCliente` INT NOT NULL,
  `prodotto_idprodotto` INT NOT NULL,
  PRIMARY KEY (`carrello_idUtente`, `carrello_Utente_idUtente`, `carrello_Utente_cliente_idCliente`, `prodotto_idprodotto`),
  INDEX `fk_carrello_has_prodotto_prodotto2_idx` (`prodotto_idprodotto` ASC) VISIBLE,
  INDEX `fk_carrello_has_prodotto_carrello1_idx` (`carrello_idUtente` ASC, `carrello_Utente_idUtente` ASC, `carrello_Utente_cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_carrello_has_prodotto_carrello1`
    FOREIGN KEY (`carrello_idUtente` , `carrello_Utente_idUtente` , `carrello_Utente_cliente_idCliente`)
    REFERENCES `mydb`.`carrello` (`idUtente` , `Utente_idUtente` , `Utente_cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrello_has_prodotto_prodotto2`
    FOREIGN KEY (`prodotto_idprodotto`)
    REFERENCES `mydb`.`prodotto` (`idprodotto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`spedizione`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`spedizione` ;

CREATE TABLE IF NOT EXISTS `mydb`.`spedizione` (
  `idspedizione` INT NOT NULL,
  `ordine_id_ordine` INT NOT NULL,
  PRIMARY KEY (`idspedizione`, `ordine_id_ordine`),
  INDEX `fk_spedizione_ordine1_idx` (`ordine_id_ordine` ASC) VISIBLE,
  CONSTRAINT `fk_spedizione_ordine1`
    FOREIGN KEY (`ordine_id_ordine`)
    REFERENCES `mydb`.`ordine` (`id_ordine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recensione`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`recensione` ;

CREATE TABLE IF NOT EXISTS `mydb`.`recensione` (
  `idrecensione` INT NOT NULL,
  `prodotto_idprodotto` INT NOT NULL,
  `voto` TINYINT(5) UNSIGNED NULL,
  `commento` VARCHAR(100) NULL,
  `data` TIMESTAMP NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idrecensione`, `prodotto_idprodotto`),
  INDEX `fk_recensione_prodotto1_idx` (`prodotto_idprodotto` ASC) VISIBLE,
  CONSTRAINT `fk_recensione_prodotto1`
    FOREIGN KEY (`prodotto_idprodotto`)
    REFERENCES `mydb`.`prodotto` (`idprodotto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
